const iconCache = new Map()

export const getIconUrl = async (searchTerm) => {
  if (iconCache.has(searchTerm)) {
    return iconCache.get(searchTerm)
  }

  // Use emoji icons directly - they're reliable and work great!
  const iconUrl = getFallbackIcon(searchTerm)
  iconCache.set(searchTerm, iconUrl)
  return iconUrl
}

const getFallbackIcon = (searchTerm) => {
  const fallbackIcons = {
    'thank you': '🙏',
    'yes': '✅',
    'no': '❌',
    'sorry': '😔',
    'hello': '👋',
    'goodbye': '👋',
    'good': '👍',
    'bad': '👎',
    'maybe': '🤔',
    'confused': '😕',
    'ok': '👌',
    'stop': '✋',
    'eat': '🍽️',
    'drink': '💧',
    'sleep': '😴',
    'work': '💼',
    'run': '🏃',
    'read': '📖',
    'walk': '🚶',
    'wake up': '⏰',
    'home': '🏠',
    'school': '🏫',
    'shop': '🛒',
    'park': '🌳',
    'hospital': '🏥',
    'church': '⛪',
    'car': '🚗',
    'boat': '⛵',
    'airplane': '✈️',
    'train': '🚂',
    'money': '💰',
    'book': '📚',
    'phone': '📱',
    'key': '🔑',
    'computer': '💻',
    'television': '📺',
    'radio': '📻',
    'delicious': '😋',
    'hot': '🔥',
    'cold': '❄️',
    'sour': '😝',
    'wet': '💧',
    'dry': '☀️',
    'mild': '🌤️',
    'cool': '😎',
    'big': '🦣',
    'small': '🐭',
    'medium': '📏',
    'tall': '📏',
    'long': '📏',
    'short': '📏',
    'fast': '💨',
    'slow': '🐌',
    'go': '➡️',
    'normal': '😐',
    'pause': '⏸️',
    'dog': '🐕',
    'cat': '🐱',
    'bird': '🐦',
    'fish': '🐟',
    'mouse': '🐭',
    'rabbit': '🐰',
    'rain': '🌧️',
    'sun': '☀️',
    'snow': '❄️',
    'wind': '💨',
    'moon': '🌙',
    'star': '⭐',
    'cloud': '☁️',
    'red': '🔴',
    'blue': '🔵',
    'green': '🟢',
    'yellow': '🟡',
    'black': '⚫',
    'white': '⚪',
    'one': '1️⃣',
    'two': '2️⃣',
    'three': '3️⃣',
    'four': '4️⃣',
    'five': '5️⃣',
    'six': '6️⃣',
    'nine': '9️⃣',
    'ten': '🔟',
    'twelve': '🔢',
    'love': '❤️',
    'hate': '💔',
    'happy': '😊',
    'sad': '😢'
  }
  
  return fallbackIcons[searchTerm] || '❓'
}